'use client'

import { useEffect, useRef } from 'react'
import type { Creature, Food } from './types'
import { WORLD_HEIGHT, WORLD_WIDTH } from './types'

type WorldCanvasProps = { creatures: Creature[]; food: Food[]; onFeed: (x: number, y: number) => void }
const TILE = 18

function seededNoise(x: number, y: number) { const value = Math.sin(x * 127.1 + y * 311.7) * 43758.5453; return value - Math.floor(value) }
function tileColor(x: number, y: number) { const noise = seededNoise(x * 0.7, y * 0.7); return noise > 0.78 ? '#4b6d30' : noise > 0.58 ? '#3d5d2a' : noise > 0.25 ? '#324a25' : '#283d22' }
function drawTree(context: CanvasRenderingContext2D, x: number, y: number, variant: number) { const shade = variant % 2 ? '#284a32' : '#31553a'; context.fillStyle = '#1e3428'; context.fillRect(x - 7, y + 10, 14, 20); context.fillStyle = shade; context.fillRect(x - 14, y - 8, 28, 20); context.fillRect(x - 10, y - 14, 20, 8); context.fillStyle = variant % 3 ? '#467241' : '#5a7d48'; context.fillRect(x - 9, y - 10, 8, 5); context.fillRect(x + 3, y - 5, 6, 5); context.fillStyle = '#a9c85d'; context.fillRect(x - 3, y - 5, 3, 3) }
function drawWater(context: CanvasRenderingContext2D, x: number, y: number, width: number, height: number) { context.fillStyle = '#155a71'; context.fillRect(x, y, width, height); context.fillStyle = '#1d7890'; for (let row = y + 6; row < y + height; row += 15) for (let col = x + ((row / 15) % 2) * 9; col < x + width; col += 27) context.fillRect(col, row, 12, 3) }
function drawTerrain(context: CanvasRenderingContext2D, width: number, height: number, offsetX: number, offsetY: number, zoom: number) { context.fillStyle = '#1b1718'; context.fillRect(0, 0, width, height); const left = Math.max(0, Math.floor(-offsetX / zoom / TILE) * TILE - TILE); const top = Math.max(0, Math.floor(-offsetY / zoom / TILE) * TILE - TILE); const right = Math.min(WORLD_WIDTH, Math.ceil((width - offsetX) / zoom / TILE) * TILE + TILE); const bottom = Math.min(WORLD_HEIGHT, Math.ceil((height - offsetY) / zoom / TILE) * TILE + TILE); context.save(); context.translate(offsetX, offsetY); context.scale(zoom, zoom); context.imageSmoothingEnabled = false; for (let x = left; x < right; x += TILE) for (let y = top; y < bottom; y += TILE) { context.fillStyle = tileColor(x / TILE, y / TILE); context.fillRect(x, y, TILE + 1, TILE + 1); const noise = seededNoise(x / TILE, y / TILE); if (noise > .84) { context.fillStyle = '#526c35'; context.fillRect(x + 4, y + 5, 2, 2); context.fillRect(x + 12, y + 12, 2, 2) } } const water = 70; drawWater(context, 0, 0, water, WORLD_HEIGHT); drawWater(context, WORLD_WIDTH - water, 0, water, WORLD_HEIGHT); drawWater(context, 0, 0, WORLD_WIDTH, 70); drawWater(context, 0, WORLD_HEIGHT - 70, WORLD_WIDTH, 70); context.fillStyle = '#161517'; context.fillRect(70, 70, WORLD_WIDTH - 140, WORLD_HEIGHT - 140); const treeStep = 32; const xStart = Math.max(90, left - (left % treeStep)); const xEnd = Math.min(WORLD_WIDTH - 90, right + treeStep); for (let x = xStart; x < xEnd; x += treeStep) { drawTree(context, x, 56, x); drawTree(context, x, WORLD_HEIGHT - 56, x + 2) } const yStart = Math.max(90, top - (top % treeStep)); const yEnd = Math.min(WORLD_HEIGHT - 90, bottom + treeStep); for (let y = yStart; y < yEnd; y += treeStep) { drawTree(context, 56, y, y); drawTree(context, WORLD_WIDTH - 56, y, y + 1) } context.restore() }
function drawFood(context: CanvasRenderingContext2D, x: number, y: number, age: number) { const pulse = Math.sin(age * 0.004) * 2; context.fillStyle = 'rgba(217, 139, 46, .25)'; context.fillRect(x - 11 - pulse, y - 11 - pulse, 22 + pulse * 2, 22 + pulse * 2); context.fillStyle = '#c57b25'; context.fillRect(x - 8, y - 8, 16, 16); context.fillStyle = '#e3a84d'; context.fillRect(x - 5, y - 5, 4, 4); context.fillStyle = '#704119'; context.fillRect(x + 3, y + 2, 3, 3) }
function drawCreature(context: CanvasRenderingContext2D, creature: Creature) { const bob = Math.sin(creature.pulse) * 2; const size = 8 * creature.scale; const color = `hsl(${creature.hue}, 58%, 58%)`; context.save(); context.translate(creature.x, creature.y + bob); context.rotate(creature.angle); context.imageSmoothingEnabled = false; context.fillStyle = '#18151a'; context.fillRect(-size - 2, -size - 2, size * 2 + 4, size * 2 + 4); context.fillStyle = color; context.fillRect(-size, -size, size * 2, size * 2); context.fillStyle = '#f2c25b'; context.fillRect(size * .1, -size * .55, 3, 3); context.fillStyle = '#2c1d21'; context.fillRect(size * .4, -size * .55, 2, 2); context.fillRect(size * .4, size * .15, 2, 2); context.fillStyle = '#f2d584'; context.fillRect(-size * .75, -size * 1.3, 3, 5); context.fillRect(size * .45, -size * 1.3, 3, 5); context.restore() }

export function WorldCanvas({ creatures, food, onFeed }: WorldCanvasProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const creaturesRef = useRef(creatures); const foodRef = useRef(food); const onFeedRef = useRef(onFeed); const viewRef = useRef({ x: 0, y: 0, zoom: 0 }); const dragRef = useRef({ active: false, moved: false, x: 0, y: 0 }); creaturesRef.current = creatures; foodRef.current = food; onFeedRef.current = onFeed
  useEffect(() => { const canvas = canvasRef.current; if (!canvas) return; const context = canvas.getContext('2d'); if (!context) return; let frame = 0; const clampView = (target: HTMLCanvasElement) => { const worldWidth = WORLD_WIDTH * viewRef.current.zoom; const worldHeight = WORLD_HEIGHT * viewRef.current.zoom; viewRef.current.x = Math.max(Math.min(0, target.clientWidth - worldWidth), Math.min(0, viewRef.current.x)); viewRef.current.y = Math.max(Math.min(0, target.clientHeight - worldHeight), Math.min(0, viewRef.current.y)) }; const resize = () => { const ratio = Math.min(window.devicePixelRatio || 1, 2); canvas.width = Math.floor(canvas.clientWidth * ratio); canvas.height = Math.floor(canvas.clientHeight * ratio); context.setTransform(ratio, 0, 0, ratio, 0, 0); const fit = Math.min(canvas.clientWidth / 2800, canvas.clientHeight / 2200) * .78; const nextZoom = Math.max(.05, Math.min(1.6, fit)); if (!viewRef.current.zoom || viewRef.current.zoom < .06) { viewRef.current.zoom = nextZoom; viewRef.current.x = (canvas.clientWidth - WORLD_WIDTH * nextZoom) / 2; viewRef.current.y = (canvas.clientHeight - WORLD_HEIGHT * nextZoom) / 2 } clampView(canvas) }; const render = () => { const { x, y, zoom } = viewRef.current; drawTerrain(context, canvas.clientWidth, canvas.clientHeight, x, y, zoom); context.save(); context.translate(x, y); context.scale(zoom, zoom); foodRef.current.forEach((item) => drawFood(context, item.x, item.y, item.age)); creaturesRef.current.forEach((creature) => drawCreature(context, creature)); context.restore(); frame = requestAnimationFrame(render) }; resize(); const observer = new ResizeObserver(resize); observer.observe(canvas); frame = requestAnimationFrame(render); return () => { cancelAnimationFrame(frame); observer.disconnect() } }, [])
  const pointToWorld = (event: { currentTarget: HTMLCanvasElement; clientX: number; clientY: number }) => { const rect = event.currentTarget.getBoundingClientRect(); const { x, y, zoom } = viewRef.current; return { x: (event.clientX - rect.left - x) / zoom, y: (event.clientY - rect.top - y) / zoom } }; const handlePointerDown = (event: React.PointerEvent<HTMLCanvasElement>) => { if (event.button !== 0) return; event.currentTarget.setPointerCapture(event.pointerId); dragRef.current = { active: true, moved: false, x: event.clientX, y: event.clientY } }; const handlePointerMove = (event: React.PointerEvent<HTMLCanvasElement>) => { const drag = dragRef.current; if (!drag.active) return; const dx = event.clientX - drag.x; const dy = event.clientY - drag.y; if (Math.abs(dx) + Math.abs(dy) > 3) drag.moved = true; viewRef.current.x += dx; viewRef.current.y += dy; drag.x = event.clientX; drag.y = event.clientY; const canvas = canvasRef.current; if (canvas) { const worldWidth = WORLD_WIDTH * viewRef.current.zoom; const worldHeight = WORLD_HEIGHT * viewRef.current.zoom; viewRef.current.x = Math.max(Math.min(0, canvas.clientWidth - worldWidth), Math.min(0, viewRef.current.x)); viewRef.current.y = Math.max(Math.min(0, canvas.clientHeight - worldHeight), Math.min(0, viewRef.current.y)) } }; const handlePointerUp = (event: React.PointerEvent<HTMLCanvasElement>) => { const drag = dragRef.current; drag.active = false; if (!drag.moved) { const point = pointToWorld(event); if (point.x >= 0 && point.x <= WORLD_WIDTH && point.y >= 0 && point.y <= WORLD_HEIGHT) onFeedRef.current(point.x, point.y) } }; const handleWheel = (event: React.WheelEvent<HTMLCanvasElement>) => { event.preventDefault(); const point = pointToWorld(event); const nextZoom = Math.max(.05, Math.min(2, viewRef.current.zoom * (event.deltaY > 0 ? .9 : 1.1))); viewRef.current.x = event.nativeEvent.offsetX - point.x * nextZoom; viewRef.current.y = event.nativeEvent.offsetY - point.y * nextZoom; viewRef.current.zoom = nextZoom; const canvas = canvasRef.current; if (canvas) { const worldWidth = WORLD_WIDTH * nextZoom; const worldHeight = WORLD_HEIGHT * nextZoom; viewRef.current.x = Math.max(Math.min(0, canvas.clientWidth - worldWidth), Math.min(0, viewRef.current.x)); viewRef.current.y = Math.max(Math.min(0, canvas.clientHeight - worldHeight), Math.min(0, viewRef.current.y)) } }
  return <canvas ref={canvasRef} className="petri-canvas" onPointerDown={handlePointerDown} onPointerMove={handlePointerMove} onPointerUp={handlePointerUp} onPointerCancel={() => { dragRef.current.active = false }} onWheel={handleWheel} aria-label="Live pixel-art Earth-scale Petri ecosystem. Click to place food, drag to pan, and scroll to zoom." role="img" />
}
